services:
  ordersservice.host:
    image: ordersservice.host
    build:
      context: .
      dockerfile: src/OrdersService/OrdersService.Host/Dockerfile

  paymentsservice.host:
    image: paymentsservice.host
    build:
      context: .
      dockerfile: src/PaymentsService/PaymentsService.Host/Dockerfile

